_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
            "2":
                - 1
                - 41
            "3":
                - 13
                - 55
            "4": 3.11.11
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
